name: GitHub Activity

on:
  schedule:
    # Runs every 30 minutes
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
